language: cpp
dist: bionic

compiler:
  - clang
  - gcc

addons:
  apt:
    update: true
    sudo: true
    packages:
      - gcc
      - g++
      - clang
      - python-yaml
      - lcov
      - libmpdec-dev
      - libfmt-dev
      - cmake
      - libboost-all-dev
      - git
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
           
    sourceline: 'ppa:ubuntu-toolchain-r/test'
    
before_script:
  - git clone -b v1.8.x https://github.com/google/googletest.git gtest
  - cd gtest && mkdir build && cd build && cmake ../ && make && sudo make install
  - cd ../../
  

script:
     - mkdir -p build
     - cd build
     - cmake -DBUILD_TESTS=ON ../
     - make
     - ctest
     - make doc
     
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_TOKEN
  local_dir: build/doc/html
  on:
    compiler: gcc
     
