language: cpp
dist: bionic
addons:
  apt:
    update: true
    packages:
      - gcc
      - g++
      - clang
      - python-yaml
      - lcov
      - libmpdec-dev
      - cmake
      - libboost-all-dev
      - git
           
    sourceline: 'ppa:ubuntu-toolchain-r/test'
    
before_script:
  - git clone -b v1.8.x https://github.com/google/googletest.git gtest
  - cd gtest && mkdir build && cd build && cmake ../ && make && make install
  

script:
     - mkdir -p build
     - cd build
     - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Coverage -DBUILD_TESTS=ON .. 
     - make
     - make project1_coverage
     - ctest
     
