language: cpp
dist: bionic
addons:
  apt:
    update: true
    packages:
      - gcc
      - g++
      - clang
      - python-yaml
      - lcov
      - libmpdec-dev
      - cmake
      - libboost-all-dev
      - libgtest-dev
      - google-mock
           
    sources:
      -  ubuntu-toolchain-r-test
        #- sourceline: 'ppa:ubuntu-toolchain-r/test'

script:
     - mkdir -p build
     - cd build
     - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Coverage -DBUILD_TESTS=ON .. 
     - make
     - make project1_coverage
     - ctest
     
