language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: true
      compiler: gcc
      addons:
      apt:
        packages: &bionic_latest_boost_packages
          - gcc
          - g++
          - clang
          - python-yaml
          - lcov
          - libmpdec-dev
          - cmake
          - libboost-all-dev
          - libgtest-dev
          - google-mock
           
        sources: &bionic_latest_boost_sources
          -  ubuntu-toolchain-r-test
        #- sourceline: 'ppa:ubuntu-toolchain-r/test'

script:
     - mkdir -p build
     - cd build
     - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Coverage -DBUILD_TESTS=ON .. 
     - make
     - make project1_coverage
     - ctest
     
