#ifndef MPDECIMAL_MPDECIMAL_NAMESPACE
#define MPDECIMAL_MPDECIMAL_NAMESPACE

#define MPDECIMAL_NAMESPACE_BEGIN namespace mpdecimal {
#define MPDECIMAL_NAMESPACE_END }

#endif // MPDECIMAL_MPDECIMAL_NAMESPACE
